env:
  global:
    # secure: h/g/KwPGkl2/eCl1ekzglUxqTkQIjzdZmgwoGpe8wLe5HvuKmjo8ZRtOpuLhfev+C/8btjIFfJ6QjOwP+Q6rafftFQ04CgRPYcDaEEM8bTwN/zZltkXXpaTuZPYQvxGfvjCyn1NpfnBWqBQNGoUXcidsyw+WqrwthcswHsH+uu8qKGO+j+3Zrf5hxgHbJV5Val8zv2EfQZiKVYs7sbnBEyOPV7SWWzuQGNd0+qjwRNfeezuHFmnINtzkFNNDU/1maeG2vpu2GtofcREkApnhFGfqNzE9eZJ8prw596BhaQLdo9LJU0cy79uqL9Gk8Z/+2UbFw7Wu0z+90XBdF91fLUDQOXtVRbWf7MImMfLfLvPBGIsG5fenKP8sgWtdnCyqs1blEm7OFiMOO6EKZJZCSw0t39Jvte0RtUQTtlGWRynKhXhJTmOdUxPHK9wm7QaFfOMlDAHrpecGgHb0T+AC/eObtwITJ3rmzEtdavZ8iiPn0B+xS9o2CPNu36JlOdm8cIyqQQD9pfEtPCbPRa8PJObV4XtyV3F8Snnkr3n2g4rmct5bjtUFrjUs1IjXvxlqL3dJh41HRxX2wvEHQm76SpIkRVjKUcJLLawCU55fGy2kYmd2ifmxv3r1ZmYRln4lHXxG8zI5iOKyf2OpEc/Rnpr/k/CxkaAhWj9Hk9/UrGQ=
    secure: e9GoqBqXMrDrybMMuqoAT/0L4I0QUff2iTUB9SIAjmmEo0M87CSFuAQcwtNjaRHH9DnF8fYrwqFY+g9KphARV4N1lEDbJzh91t0ic4j0aTOR5pGCdfVsMI+TmIlD+A9Ed/yQNyZQtYZyQeYxiQCT7UCxvgOTvCErm6jAbkrBpV4yPG7617i/ddlpu1N8JCfs4WAKXS4o6DrxhQUikCMyznUB6xZLWNgGonZ+7NED/Nzld6wl0UUMDfZqrNacjMpPge/MlwwaWifK7SUzh4fP1lPAFzpVUsYwsMlUJiQU/g1nbCfJ5wL8K5Dp+ivEMusQNiWyEGR8LucO8S1ZpfJYn0jFWOnPfU0K0638LSZ9ikWTUV7w3bPTPg5NOIbiEP4ocAPd7jDKeU9UkmHRgSes1MwRpoUIwgeOe4G3CtR2qRbldD5IPBbnxlRUHyGoJu1HPS1DtRBHpASynQ+iTAffB49Nvq0Z/izF5v8u316qaLWpIlLTa/9edw5FTs26gj+83pEdsW0jwuXPE+ZLJEDKQWRK9FWjlYeBIoBq1BiDFCB+C7QDLJyuFIzeTV5c2SmKeRzSGRbwq2rOYAiNr/A63wQ3jbRqfn0zaOAwnBw7iZFHZK3R+gwD+WPWp62pXuAhhEC8Q9F03pJ+Orrryy/LVI0Kuzq/f8ODrZzHQzvaj2I=
language: node_js
node_js:
  - node
services:
  - docker
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - audit-ci --moderate
  - yarn run build
  - yarn run watch &
  - sleep 5
  - yarn upgrade @spectrum-css/spectrum-css-vr-test-assets-essential
  - cp -R ./node_modules/@spectrum-css/spectrum-css-vr-test-assets-essential/bitmaps_reference/ backstop_data/
  - yarn run backstop:ci:test themes=light scales=medium reference=backstop_data/bitmaps_reference/
after_failure:
  - ./backstop_data/deploy_comment.sh
